template_path: "accounts.yaml"
stack_name: "accounts"
dependencies:
  - "prod/essentials.yaml"
  - "prod/sc-enduser-iam.yaml"
  - "prod/sc-enduser-dev-iam.yaml"
parameters:
  InitNewUserPassword: !ssm "/infra/InitNewUserPassword"
