template_path: remote/ParkMyCloud.yaml
stack_name: park-my-cloud
dependencies:
  - prod/bootstrap.yaml
parameters:
  PMCExternalID: !ssm /infra/PMCExternalID
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/ParkMyCloud.yaml --create-dirs -o templates/remote/ParkMyCloud.yaml"
