template_path: "remote/sc-enduser-iam.yaml"
stack_name: "sc-enduser-iam"
dependencies:
  - "prod/essentials.yaml"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/scipoolprod-sc-lib-infra/master/iam/sc-enduser-iam.yaml --create-dirs -o templates/remote/sc-enduser-iam.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/scipoolprod-sc-lib-infra/master/iam/sc-enduser-iam.yaml --create-dirs -o templates/remote/sc-enduser-iam.yaml"
