template_path: remote/cfn-oidc-identity-provider.yaml
stack_name: synapse-oidc-idp
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Url: "https://repo-prod.prod.sagebase.org/auth/v1"
  ClientIDList: "100001"
  ThumbprintList: "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
hooks:
  before_launch:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/cfn-oidc-identity-provider.yaml --create-dirs -o templates/remote/cfn-oidc-identity-provider.yaml"
